### ISSUE TITLE
Open Form Seen ONLY by the User.

### ISSUE THREAD

**Issue by DKLeoBR** [TheSph1nx/RT-101#5]
Using RDP, how can i Open a form seen ONLY by the user?

User, for exemple, see a Overlay form with "Please Wait" and a Progress bar, for example
But ONLY the user will see this ONTOP form.

The controller will NOT see this form on RDP and can still controlling the remote computer with keyboard/mouse events.

Its possible? how? Thanks.

**Comment by TheSph1nx** [comment]
The RDP on my rat actually works in this way :

Takes a screenshot from the remote screen
Send it to the server

So when you start the RDP you'll see everything open on the the remote machine.
If we can create a custom form with the progress bar as you said the RDP attacker will still see this form open on the remote machine because this is not a REAL remote desktop protocol.

In the end I think you can't make what you're asking for. Or maybe i've misunderstood.

**Comment by DKLeoBR** [comment]
When this print is captured, isn't there any kind of parameter I can implement to ignore a window, or a specific pid of this screenshot?

Same thing when sending a Mouse and Keyboard event. ignore a specific window.

The idea is to load a Form.
Form2.Visible = True

But only the clients sees this form.

The attacker does not see it and continues to use Remote Desktop normally behind this form.

I saw it being done in front of me. I know it's possible to do it, I've seen it happen. I just don't know how.

**Comment by TheSph1nx** [comment]
Actually you could do it , I didn't say that, but not using the built in RDP method I've created. You could create your own RDP that takes the screenshots of each open window parsing it by the title, capturing the coordinates of them and writing the final screenshot but it's really complex to do .
